# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=150)),
                ('userGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.UserGroup')),
            ],
        ),
    ]
